// Autogenerated, do not edit. All changes will be undone.
"use strict";

angular.module("fbPostImageValidator").constant("fbPostImageValidator.constants.imgCaseStates", {
  VALID: 1,
  INVALID: 0,
  UNDEFINED: -1
});